{% set name = "quetz-client" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/quetz_client-{{ version }}.tar.gz
  sha256: c955f6e60f08340a42e30d15b318d54e1c70dd8be3cf454a195db30f6414c4e4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  entry_points:
    - quetz-client = quetz_client.cli:main

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - fire
    - requests
    - dacite

test:
  imports:
    - quetz_client
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mamba-org/quetz-client
  summary: A Python client to interact with a Quetz server.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariobuikhuizen
    - wolfv
    - janjagusch
