{% set name = "quetz-client" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/quetz_client-{{ version }}.tar.gz
  sha256: e4a7a5bf437bd372f773e286426d970583e2c5c658190d48eb8002862f0a741f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - quetz-client = quetz_client.cli:main

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.8
    - fire
    - requests
    - dacite

test:
  imports:
    - quetz_client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mamba-org/quetz-client
  summary: A Python client to interact with a Quetz server.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariobuikhuizen
    - wolfv
    - janjagusch
